### PR TITLE
Should not magically convert kebab-cased values to camelCased values

### LINKED ISSUE #12: should not handle class-name as class property
Please have a look here https://github.com/Prettyhtml/prettyhtml/issues/42

### PR DESCRIPTION
**Pull request by StarpTech**
Failing tests to reproduce will fix #12

### CODE REVIEW

**Comment by wooorm** [comment]
Wait, could you provide us with some more info?

**Comment by StarpTech** [comment]
Please ask any specific question. The current implementation handles an attribute with the name `class-name` as `class` property because after normalization the delimiter is removed and transformed to lowercase. This PR will fix this situation. I don't know if it's 100% correct but all tests are passed.

**Comment by StarpTech** [comment]
@wooorm is it clear now?

**Comment by wooorm** [comment]
Ah, missed that. Thanks Dustin!

I feel this is similar to https://github.com/wooorm/property-information/issues/11#issuecomment-425344808. It feels like you want something that never normalises values, whereas this project is meant for the normalising part 🤔

**Comment by StarpTech** [comment]
> I feel this is similar to #11 (comment). It feels like you want something that never normalises values, whereas this project is meant for the normalising part

No, it's not related because we will always lowercase the attributes. I'm fine with normalization but my idea in #11 was to respect case-sensitivity when the known attribute isn't supported by the tag.

According to this issue can we merge and release it?

**Comment by wooorm** [comment]
@StarpTech The `:` and `-` stripping is I believe pretty important, if you remove it, everything breaks: SVG, XML, XLink, and XMLNS completely, `accept-charset` / `http-equiv` in HTML. 🤔

Could you try adding some tests showing they don’t break?

**Comment by StarpTech** [comment]
There are already tests for `-`, `:` Could you tell me a specific example?
It works because the `normal` property of the schema maintains a list of normalized + unnormalized values:

```
{ xmllang: 'xmlLang',
  'xml:lang': 'xmlLang',
  xmlbase: 'xmlBase',
  'xml:base': 'xmlBase',
  xmlspace: 'xmlSpace',
  'xml:space': 'xmlSpace',
  xlinkactuate: 'xLinkActuate',
  'xlink:actuate': 'xLinkActuate',
  xlinkarcrole: 'xLinkArcRole',
  'xlink:arcrole': 'xLinkArcRole',
  xlinkhref: 'xLinkHref',
  'xlink:href': 'xLinkHref',
  xlinkrole: 'xLinkRole',
  'xlink:role': 'xLinkRole',
  xlinkshow: 'xLinkShow',
  'xlink:show': 'xLinkShow',
  xlinktitle: 'xLinkTitle',
  'xlink:title': 'xLinkTitle',
  xlinktype: 'xLinkType',
  'xlink:type': 'xLinkType',
```
and when the attribute is defined it can be just returned https://github.com/wooorm/property-information/blob/master/find.js#L21

**Comment by wooorm** [comment]
@StarpTech Ahh I forgot about that. Sorry!

Well then I’m fine with this change, as long as it’s properly documented and tested, and in a major release!

**Comment by StarpTech** [comment]
@wooorm doc was updated!

**Comment by StarpTech** [comment]
@wooorm I'm not aware of any additional test-scenario. If you find something ping me. It would be great when we can merge it.

**Comment by StarpTech** [comment]
@wooorm ping.

**Comment by StarpTech** [comment]
@wooorm this test will fail https://github.com/syntax-tree/hastscript/blob/master/test.js#L148. It seems that the current behaviour was intentional?

**Comment by wooorm** [comment]
@StarpTech sorry for the delay!

Yes, it was intentional to be chill about input, but maybe that’s not good.
Anyway, this will be a breaking change, so I’m a bit hesitant in doing a major release of all the rehype and hast packages!

**Comment by StarpTech** [comment]
@wooorm I think this change will definitely improve the handling because as you see this issue comes from real-world user experience 😄

**Comment by StarpTech** [comment]
> Yes, it was intentional to be chill about input, but maybe that’s not good.
Anyway, this will be a breaking change, so I’m a bit hesitant in doing a major release of all the rehype and hast packages!

You don't agree with the change or what's the problem?

**Comment by wooorm** [comment]
@StarpTech I agree with the change, just don’t want to do major releases too often if they‘re only tiny changes (but still breaking)

**Comment by StarpTech** [comment]
Just as a reference: [Here](https://github.com/Prettyhtml/prettyhtml/issues/50) is another user which use the attribute `item-type` but due to the normlization process it is transformed to `itemtype`

When can we expect a major release? What's wrong with the circumstance that not every package is up-to-date when it's from your side, not a critical issue?

**Comment by StarpTech** [comment]
@wooorm would be great to have a decision 🤔 so that I can think about a different solution for my project.

**Comment by StarpTech** [comment]
@wooorm ping!

**Review by wooorm — APPROVED** [review]

**Pull request merged**
